export default {
    products: [
        {
            _id: '1',
            name: 'Mini Handheld Portable Fan',
            category: 'Summer',
            image: 'fan1.jpg',
            price: 13.99,
            brand: 'IPOW',
            rating: 4.8,
            numReviews: 625,
            description: '',
            countInStock: 0,
        },
        {
            _id: '2',
            name: 'Mini Flexible Tripod Clip On Fan',
            category: 'Summer',
            image: 'fan2.jpg',
            price: 19.99,
            brand: 'Amacool',
            rating: 4.9,
            numReviews: 2589,
            description: '',
            countInStock: 7,
        },
        {
            _id: '3',
            name: 'Portable Neck Fan',
            category: 'Summer',
            image: 'fan3.jpg',
            price: 19.99,
            brand: 'IPOW',
            rating: 4.5,
            numReviews: 1623,
            description: '',
            countInStock: 10,
        },
        {
            _id: '4',
            name: 'Lady Handheld Portable Fan',
            category: 'Summer',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51kxZt06SUL._AC_SL1000_.jpg',
            price: 13.99,
            brand: 'IPOW',
            rating: 4.4,
            numReviews: 869,
            description: '',
            countInStock: 8,
        },
    ]
}